# Generated by Django 5.1.7 on 2025-03-31 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatconversation',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Conversación', 'verbose_name_plural': 'Conversaciones'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='browser_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='source_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='user_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='detected_entities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='detected_intent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='processing_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='session_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TrainingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_response', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_feedback', to='chatbot.chatmessage')),
            ],
            options={
                'verbose_name': 'Retroalimentación para entrenamiento',
                'verbose_name_plural': 'Retroalimentaciones para entrenamiento',
            },
        ),
    ]
